### ISSUE TITLE
Securing web API using TLS

### ISSUE THREAD

**Issue by nettoclaudio** [tsuru/rpaas-operator#40]
It would be nice if we run the web API under the TLS, this would make life harder for the bad guys. :closed_lock_with_key:

We can use the `config` package to read the path in the system which is located the certificate and key. A good name to these is `RPAASV2_API_CERTIFICATE` and `RPAASV2_API_KEY` respectively.

**Comment by pedrokiefer** [comment]
@nettoclaudio should this variables be env-vars or embedded inside `RpaasConfig`?

**Comment by nettoclaudio** [comment]
I would put into `RpaasConfig`, it seems to be more clear to me. On `config.Init` function, we already implement two ways to get those configs (from env var and/or config file), you would just adapt adding the new ones.

**Comment by nettoclaudio** [comment]
Closed due PR #41.
